{% set version = "1.0-5" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-blme
  version: {{ version|replace("-", "_") }}

source:
  fn: blme_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/blme_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/blme/blme_{{ version }}.tar.gz
  sha256: 679a4f19d34a584c2390ffab37810a31f6834b913fceaa2409d297ccdf912310

build:
  noarch: generic
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-lme4 >=1.0_6

  run:
    - r-base
    - r-lme4 >=1.0_6

test:
  commands:
    - $R -e "library('blme')"  # [not win]
    - "\"%R%\" -e \"library('blme')\""  # [win]

about:
  home: https://github.com/vdorie/blme
  license: GPL (>= 2)
  summary: Maximum a posteriori estimation for linear and generalized linear mixed-effects models in a Bayesian setting. Extends 'lme4' by Douglas Bates, Martin Maechler, Ben Bolker, and Steve Walker.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - ccwang002
