travis:
  secure:
    BINSTAR_TOKEN: W1Mq4dPFZPpjuT2RPW4/6Jb+jzRAgpjIfbGUNDDSP1Z6sPwHN9hqTED5FnwK64Q2uMHGTRqZg2Afk6VV6QrKFxmLzlg20hZfBjXnYp9Ek9SGl62KwJAgseqWa/raGPkYlW0qWFhmzy2LSyTa9n3cxtkE+ZzRIYCLlRcRVcv6reC+Rxy3B3XDeCAuBhrF1xOrZOave7Wz++YMYGZj6o+6btWdtF0VCHNfyC806c9m3gAMgQ0PmIeRKZckWUaZX5TXFn76ij3Ii1o4vT6Zm9qCZT1g+gHzViE15dEL16T6K5OaxeW6MopZQxVxJIAG/0UoXd6zWpG11/DXYoTFuIvqdZxMk2BzVi+QtxZZhOSN+pfUvKa/sLZM1ibF2o2JyWIW7AJCl8c0eeTlM9LrR8D2jw83jLCV0izMVJgHRZKXQFauoX5VGpdFvI009uqKBarsJnt5MVlaYJjEJYkbswa5mTk0RE/xEFGFWN4kVSunHCCvIggGgRKZCpDpwgC6nmnlZekU/x3RkBLeiEPB+t8WwGx2fXp+RtMkD7q+VbXvrAgHegNeotqIKwVBMr0mOIc6d+j7f5ic3FtfJO+CtWbT+QyhZMrXlhhWA0nMoGhxQ6LpVPc7VBNKsRA6wPUgvqoZhEs7FE0ItR6eOXl1j/+zSWNMf0We50TqFRGGGEq/O/Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
