appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: lIIuvmgEj5kHaaWr9A/k0Z0CGJE0GRZ1ZNOK4rZGnpIQiVcSVPupMOTdv2uMvl4IPWcII/tIQWKmPEmha7vqwV2yk23uBBX21crCuD/Qb8xGd0WZcEwgypq+ksaVSjybSZ4gE1lWwymjNFNnbMNB2TFcV1r4Z8HVD9yr7vUBU8v1mh/9sf3F+cmHKBbz3DJroBChL4t+/O4n2/UhmTuiuYfEp7FFFeWU2vZQPFrADynjD7QknpDp6FomD8pJRBvJry4oHvNx4egDBWgrLwQQ5JlM7w8he1+IW+F1mV548W7ejcNl4BXBH+henUysnFXHh3wZ6to2RtjJUYnw/0adCHGmll6ySXh3/nSnsc/PgCA8dgjxfxuW4ymFCRsKOEwhONk4/Vkwg45wIneB3lJyFvCh13sdICgoG7xo2J58DVy7ANcOUV25ITZXcFXEQTwUvXwYBmeWZawB2qtzZ8l7cY0gwVa/F+sNbW0AwJtpuB/+kGef7qQZzTzEixR6mX8YVGWi00Ks+B+Q1y/Bl9PvIBzP1YW00us3tl8TpEYU0i1KZo7f9j/aFvCV4Tzug57Yy848ad8kfoFEsUD7YI6LnJm3ZFncCsw/mWg8Rg0Zed0ByDStgqLzkPy0Y65c94tMmvSiz4+wNiQwtSBo6FxijHAMzxj2zlYFoxVxVYnaOiQ=
